---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
##Load packages
```{r echo=TRUE}

library(dplyr)    

```

## Loading and preprocessing the data
```{r loadData, echo=TRUE}

setwd("D:/New_folder/RepData_PeerAssessment1/")

steps <- read.csv("activity.csv")

steps$date <- as.Date(as.character(steps$date))
steps$date <- format(steps$date, "%m/%d/%y")
steps$date <- format(steps$date, "%Y-%m-%d")
str(steps)

```

## What is mean total number of steps taken per day?
```{r total_mean_median_Steps, echo=TRUE, results="asis"}

library(xtable)

steps_total <- steps %>%
  group_by(date) %>%
  summarize(sum = sum(steps))

hist(steps_total$sum)

steps_mean <- steps %>%
  group_by(date) %>%
  summarize(mean = mean(steps))

stepsmean_table <- xtable(steps_mean)

print(stepsmean_table, type = "html")

steps_median <- steps %>%
  group_by(date) %>%
  summarize(median = median(steps))

stepsmedian_table <- xtable(steps_median)

print(stepsmedian_table, type="html")

```


## What is the average daily activity pattern?
```{r avgdailyactivity, echo=TRUE}

library(ggplot2)

stepsint_avg <- steps %>%
                  group_by(interval) %>%
                  summarize(meanInt = mean(steps, na.rm=TRUE))

tbl_df(stepsint_avg)

ts_int <- ggplot(data=stepsint_avg, aes(x=interval, y=meanInt))  + geom_line() + ggtitle("Average Steps Taken by Interval Across All Days") +xlab("Interval") + ylab("Average Steps")

ts_int

max_avg_int <- filter(stepsint_avg, meanInt == max(stepsint_avg$meanInt))

max_avg_int$interval


```


## Imputing missing values
```{r missingVals, echo=TRUE, results = "asis"}

missing_count <- sum(is.na(steps$steps))

missing_count

steps_meanInt1 <- steps %>%
    group_by(interval) %>%
    mutate(meanIntsteps = mean(steps, na.rm=TRUE))

steps_meanInt1

steps_meanInt1$steps <- ifelse(is.na(steps_meanInt1$steps) == TRUE, steps_meanInt1$meanIntsteps, steps_meanInt1$steps)

steps_meanInt1

steps_meanInt1 <- data.frame(steps_meanInt1[c(1:3)])

str(steps_meanInt1)

steps_meanInt_sum <- steps_meanInt1 %>%
                      group_by(date) %>%
                      summarize(sum = sum(steps))


hist(steps_meanInt_sum$sum)

steps_meanInt_mean <- steps_meanInt1 %>%
                      group_by(date) %>%
                      summarize(mean = mean(steps))

steps_meanInt_mean_table <- xtable(steps_meanInt_mean)

print(steps_meanInt_mean_table, type="html")

steps_meanInt_median <- steps_meanInt1 %>%
                      group_by(date) %>%
                      summarize(median = median(steps))
                      

steps_meanInt_median_table <- xtable(steps_meanInt_median)

print(steps_meanInt_median_table, type="html")

mean_comparison <- merge(steps_mean,steps_meanInt_mean, by.x="date", by.y = "date" )

mean_comparison

mean_comparison_table <- xtable(mean_comparison)

print(mean_comparison_table, type="html")

median_comparison <- merge(steps_median, steps_meanInt_median, by.x = "date", by.y = "date")

median_comparison

media_comparison_table <- xtable(median_comparison, type="html")

sum_comparison <- merge(steps_total, steps_meanInt_sum, by.x="date", by.y="date")

sum_comparison_table <- xtable(sum_comparison)

print(sum_comparison_table, type = "html")

steps$weekday <- weekdays(as.Date(steps$date))

str(steps)

table(steps$weekday)

steps$day_type <- gsub('Saturday|Sunday', 'weekend',steps$weekday )

steps$day_type1 <- gsub('Monday|Tuesday|Wednesday|Thursday|Friday', 'weekday',steps$day_type )

table(steps$day_type1)

```



## Are there differences in activity patterns between weekdays and weekends?

```{r}

str(steps_meanInt1)
steps$weekday <- weekdays(as.Date(steps$date))
table(steps$weekday, useNA="always")

steps_meanInt1$betterdate <- as.Date(steps_meanInt1$date, "%m/%d/%y")

str(steps)

steps_meanInt1$weekday <- weekdays(steps_meanInt1$betterdate)

table(steps_meanInt1$weekday)

steps_meanInt1$day_type <- gsub('Saturday|Sunday', 'weekend',steps_meanInt1$weekday )

steps_meanInt1$day_type1 <- gsub('Monday|Tuesday|Wednesday|Thursday|Friday', 'weekday',steps_meanInt1$day_type )

table(steps$day_type1)

steps1 <- steps %>% 
          group_by(interval, day_type1) %>%
          summarize(meanint1 = mean(steps, na.rm=TRUE))

steps1

g01 <- ggplot(steps1, aes(interval, meanint1))
p01 <- g01 + geom_point(size=2, color = "purple") + facet_grid(. ~ day_type1) + 
  geom_line(color="brown") + ylab("Average") +
  labs(title = "Average") 

print(p01)

```


